### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by JavierMartinz**

### CODE REVIEW

**Review by kentcdodds — CHANGES_REQUESTED** [review]
Thanks, but this is correct as-is. The word is "do" with emphasis, so it's all caps. You could bold it instead if you think that would be more clear.

**Comment by JavierMartinz** [comment]
I'd say it's more clear this way

**Review by kentcdodds — APPROVED** [review]
Thanks!

**Comment by kentcdodds** [comment]
@all-contributors please add @JavierMartinz for content

**Pull request merged**
