### PR TITLE
Fix links

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
- Fix outdated `downshift` links
- Fix outdated `react-testing-library` links
- Fix outdated `jest-dom` links
- Fix outdated `all-contributors` links
- Fix outdated `cypress-testing-library` links
- Fix outdated `dom-testing-library` links
- Fix kentcdodds.com links
- Add following redirects
  - `https://blog.kentcdodds.com/the-state-reducer-pattern--b40316cfac57` -> `/blog/the-state-reducer-pattern`
  - `https://blog.kentcdodds.com/testing--components-using-render-props-5623ab1814c` -> `/blog/testing-components-using-render-props`
  - `https://blog.kentcdodds.com/react-is-an-implementation-detail-and-course-faq-ee73b028745e` -> `/blog/react-is-an-implementation-detail`

The following links doesn't exist anymore:
- https://blog.kentcdodds.com/announcing-something-new-4e68b08da35
- https://blog.kentcdodds.com/did-you-know-3079d5aec43b

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Wow. This is amazing. Thank you so much!

**Comment by kentcdodds** [comment]
@all-contributors please add @MichaelDeBoey for content

**Comment by MichaelDeBoey** [comment]
With pleasure! 🙂

**Comment by MichaelDeBoey** [comment]
@kentcdodds The redirected links still don't work... 😕
- https://blog.kentcdodds.com/the-state-reducer-pattern--b40316cfac57
- https://blog.kentcdodds.com/testing--components-using-render-props-5623ab1814c
- https://blog.kentcdodds.com/react-is-an-implementation-detail-and-course-faq-ee73b028745e

So I think my changes in `static/_redirects` don't work

**Comment by kentcdodds** [comment]
I had wondered about those changes. That's a different domain so the _redirects in this repo wont effect those. You're looking for [this one](https://github.com/kentcdodds/kcd-blog-redirector/blob/master/_redirects). Where are you seeing those links?

**Comment by MichaelDeBoey** [comment]
@kentcdodds these were in the code, but I refactored them to the correct link

But maybe there are existing links out there that won’t redirect correctly now? 🤔

**Comment by kentcdodds** [comment]
I think I fixed them here: https://github.com/kentcdodds/kcd-blog-redirector/commit/8a103c73a1ca17d9a5b19597f7ef405cefe3f4f6

Thank you for your help!

**Comment by MichaelDeBoey** [comment]
Fixed it indeed 🙂

**Pull request merged**
