### PR TITLE
Wrap tags on presentation items

### PR DESCRIPTION
**Pull request by jgierer12**
Fixes [this issue](https://mobile.twitter.com/jgierer12/status/1094146272183885824) by allowing tags to wrap to the next line.

Also adds a small gap between heading and tags.

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Thank you!

**Comment by kentcdodds** [comment]
@all-contributors please add @jgierer12 for code

**Comment by jgierer12** [comment]
Thanks! I didn't know there was a bot for AC. Very cool!

**Comment by kentcdodds** [comment]
It's pretty new! I love it!

**Pull request merged**
