### PR TITLE
Add clear takeaway and approach

### PR DESCRIPTION
**Pull request by coryhouse**
This is an excellent post and useful insight. 👍 But the end left me unclear: What's my action item? I've added one.

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Thank you Cory! I knew I needed something like this, but I kinda forgot to add it 😅

**Comment by kentcdodds** [comment]
@all-contributors please add @coryhouse for content

**Comment by coryhouse** [comment]
FYI - "without the needing" -> "without the need"

**Comment by kentcdodds** [comment]
Ah, thanks. I'll fix that :)

**Pull request merged**
