### PR TITLE
remove 🧹/ accent from autolink headers

### PR DESCRIPTION
**Pull request by jeltehomminga**
<blockquote class="twitter-tweet"><p lang="en" dir="ltr"><a href="https://twitter.com/kentcdodds?ref_src=twsrc%5Etfw">@kentcdodds</a> hi Kent, just a heads up seems that your anchor url addresses are broken in the article I checked. The slash is missing. for example <a href="https://t.co/bqksBZQsDO">https://t.co/bqksBZQsDO</a> instead of <a href="https://t.co/wmyDRHOwCO">https://t.co/wmyDRHOwCO</a></p>&mdash; Jelte ⚛ (@JelteHomminga) <a href="https://twitter.com/JelteHomminga/status/1272777961574477824?ref_src=twsrc%5Etfw">June 16, 2020</a></blockquote> 

I removed the removeAccents: true, option from 'gatsby-remark-autolink-headers'. This fixes the issue that the trailing slash that is needed will not be removed anymore. I searched some info the accents are needed, but as far as I can find not.

[google-accents-in-urls](https://www.seroundtable.com/google-accents-in-urls-seo-27314.html)

So this seems fine to me unless there is a specific reason you want to use this option. Hope this helps. keep up the great work!

### CODE REVIEW

**Comment by kentcdodds** [comment]
Thanks for this @jeltehomminga!

Could you tell me which link isn't working? They all seem to be working fine for me as-is.

**Comment by jeltehomminga** [comment]
the shareable anchor link addresses are not working properly. It seems the same for all of them. So I wanted to share the "Then I discovered msw" part of the page https://kentcdodds.com/blog/stop-mocking-fetch. So I copied the link address on the anchor before the heading "Then I discovered msw". 

However this address brings you to the top of the page as new visiter to the page. If I look at the url then it seems a slash is missing before the hash, if I add it manually it works

so the copied addres https://kentcdodds.com/blog/stop-mocking-fetch#then-i-discovered-msw doesn't take you to the right part of the page, but brings you to the top. 

If you add a slash like  https://kentcdodds.com/blog/stop-mocking-fetch/then-i-discovered-msw it takes you to the right part of the page

**Comment by kentcdodds** [comment]
@all-contributors please add @jeltehomminga for code

**Comment by kentcdodds** [comment]
Thanks :)

**Pull request merged**
