### PR TITLE
kent.png image is optimized (Very tiny PR)

### LINKED ISSUE #28: Reduce the size of kent's image ?
By the way site looks grt 👍 

But one thing I noticed while loading was @kentcdodds your avatar image in home page takes time to load although you have `the service worker` to cache the subsequent request. But initial load is could be little faster if we optimize the kent.png image in hero folder.

Attaching an optimized version of it.

Its `127KB`. Original was around `500KB`

kent-optimizied

### PR DESCRIPTION
**Pull request by gokulkrishh**
This closed #28

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Awesome! Thanks!

**Comment by kentcdodds** [comment]
@all-contributors please add @gokulkrishh for content

**Comment by MichaelDeBoey** [comment]
@gokulkrishh How did you optimize the image? 🤔

@kentcdodds How do you optimize your banner images?

**Comment by kentcdodds** [comment]
I use tinypng.com for one-offs and when I generate a new blog post I use its API: https://github.com/kentcdodds/kentcdodds.com/blob/master/generate/blogpost.js#L101

**Pull request merged**
