### PR TITLE
feat: enable lazy image processing alpha

### PR DESCRIPTION
**Pull request by wardpeet**
We've created a canary version of plugin sharp that does lazy image processing during develop. This should drastically speed up develop time. It's still in alpha stage but it's worth testing.
We haven't officially launched it yet but I would like you to check it out :)

You can disable the feature by setting `experimentalDisableLazyProcessing: false`.

### CODE REVIEW

**Comment by kentcdodds** [comment]
This is very encouraging! Let me know when it's stable :) Thanks!

**Comment by wardpeet** [comment]
I've tested it on your site and it works fine. There might be issues when you switch between develop & build on your local machine. On netlify where you only run one command it's not an issue.

But I get your hesitation ;) 

```
8:19:28 PM: > kentcdodds.com@1.0.5 netlify /opt/build/repo
8:19:28 PM: > GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES=true gatsby-parallel-runner
8:19:29 PM: You must set a GOOGLE_APPLICATION_CREDENTIALS environment variable
```

I get these errors during the netlify deploy.

**Comment by JacobMGEvans** [comment]
Hey, @wardpeet I just wanted to follow up with you on this. Any plans to update the PR?

**Comment by JacobMGEvans** [comment]
Gatsby is being replaced with Remix

**Pull request closed without merging**
