### PR TITLE
Fix typo in useeffect vs uselayouteffect article

### PR DESCRIPTION
**Pull request by cascandaliato**
safly -> safely

### CODE REVIEW

**Review by JacobMGEvans — APPROVED** [review]
Nice catch!

**Review by kentcdodds — APPROVED** [review]
Thanks!

**Comment by kentcdodds** [comment]
@all-contributors please add @cascandaliato for content

**Comment by kentcdodds** [comment]
@all-contributors please add @JacobMGEvans for review

**Comment by cascandaliato** [comment]
You're welcome.

I like your articles, and especially this one because I had to use `useLayoutEffect` few days ago.

**Pull request merged**
