### PR TITLE
Fixing JSON parse error in request

### PR DESCRIPTION
**Pull request by danielghandahari**
I used the fetch-wrapper and ended up with this when my server responded with 404: `SyntaxError: Unexpected token <first character in server error message> in JSON at position 0`, whereas I wanted to see the server error. The line `const data = await response.json()` fails the whole promise and Promise.reject is never reached. Skipped changing other parts since they refered to the bookshelf app. Appreciate all your great content!

### CODE REVIEW

**Review by kentcdodds — COMMENTED** [review]
Good call! Want to fix the other spots this is broken?

Also, I don't think we need the extra parentheses around `(await response.json())`

**Comment by danielghandahari** [comment]
Sure! :)

**Review by kentcdodds — APPROVED** [review]
Super, thanks!

**Comment by kentcdodds** [comment]
@all-contributors please add @danielghandahari for content

**Pull request merged**
