### PR TITLE
Add link to Brazilian Portuguese Translation

### PR DESCRIPTION
**Pull request by ghost**
I found your article so helpful that felt the need to translate it. Thank you.

### CODE REVIEW

**Comment by ghost** [comment]
May I also translated this [referenced article](https://kentcdodds.com/blog/react-hooks-array-destructuring-fundamentals)?

**Review by kentcdodds — APPROVED** [review]
Awesome! Thank you :)

**Comment by kentcdodds** [comment]
And yes, you definitely can translate that other article :) Thank you!

**Comment by kentcdodds** [comment]
@all-contributors please add @mjfneto for translations

**Pull request merged**
